esphome:
  name: chambre
  friendly_name: chambre

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "38b3/QxsWqLbHfDmfLWjzaPEADK5ZwLzwDwymdNtW4E="

ota:
  - platform: esphome
    password: "e831a0604f4928e7c09e0ecc80aadaec"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Chambre Fallback Hotspot"
    password: "7UeSZuvNLThi"

captive_portal:
    